### ISSUE TITLE
Thermostate MQTT deivery

### ISSUE THREAD

**Issue by fraintt** [fraintt/dummy_conversation#1]
(follow-up of the conversation )
@robertorobles How do you send mqtt messages to the thermostate? Via HASS climate config, or mqtt broker?

**Comment by robertorobles** [comment]
mqtt broker

**Comment by fraintt** [comment]
check if you are sending to the correct mqtt address, in your thermostate config xx.xx.xx.xx/config at the top you should have "Idx: " 
something like: thermostat_123456, copy that, and try to send to the topic "thermostat_123456/thermostat/set/TargetTemperature" the data: "21.0" (without quotation marks) which should set the temp to 21 deg.

**Comment by robertorobles** [comment]
@fraintt I share you a video https://drive.google.com/file/d/1tpkGkTc4begTLWIY5isxfcqKjrlQR0T-/view?usp=share_link
As you can see, at first I changed the temperature several times, when I tried to change to 19 it didn't work (it's a bit random).
After I disabled the QueryMCU option, it stopped receiving/sending MQTT messages.
I turned the QueryMCU option back on and it is receiving/sending MQTT messages again.

**Comment by fraintt** [comment]
try to uncheck all of the checkboxes, thats what I have. also, try to send really "18.0" with the dot, and zero at the end. 

Keep in mind that the first checkbox overrides the manual mode to automatic. 
I once troubleshooted why my thermostate was changin all the time when I have set it to manual mode, and this checkbox was checked. It writes there that it does not work, but it works.

**Comment by robertorobles** [comment]
I have unchecked the "auto mode" box, I get the same result.
I tried to send with decimal and without it, but the same thing happens.

**Comment by fraintt** [comment]
and when you send these values, does actually anything change on your thermostate?
Also, by any change, have you sent any mqtt message in the past with the "retain" flag set to true?

**Comment by robertorobles** [comment]
No, the thermostate doesn't change. Only change with the QueryMCU option activated.
I don't know how send the retain flag, so I always send with this value to false.

**Comment by robertorobles** [comment]
do you have the ME81H too?

**Comment by fraintt** [comment]
Yes, I have the me81H too. 

Okay, lets try a different thing. Apply the following config into your configuration.yaml
restart hass or in developer-tools reload mqtt entities
afterwards search for the climate entity, and try to change the values from hass. 

(just change the topic values and ip to your own )

```
  climate:
    - name: Living Thermostat
      unique_id: termostat
      device:
        configuration_url: http://your-ip/config
        manufacturer: Tuya
        model: ME81AH
        connections: [["mac", "xx:xx:xx:xx:FF:FF"]]
      temperature_command_topic: thermostat_123456/thermostat/set
      temperature_command_template: >
        {{ {'TargetTemperature':value} | to_json }}

      temperature_state_topic: thermostat_123456/thermostat/properties
      temperature_state_template: >
        {% if value_json is defined and value_json['TargetTemperature'] is defined %}
          {{ value_json['TargetTemperature'] }}
        {% endif %}  
      current_temperature_topic: thermostat_123456/thermostat/properties
      current_temperature_template: >
        {% if value_json is defined and value_json['Temperature'] is defined %}
          {{ value_json['Temperature'] }}
        {% endif %}  
      mode_state_topic: thermostat_123456/thermostat/properties
      mode_state_template: >
        {% if value_json is defined and value_json['deviceOn'] is defined %}
          {% set deviceOn = value_json['deviceOn'] %}
        {% else %}
          {% set deviceOn = false %}
        {% endif %}
  
        {% if value_json is defined and value_json['schedulesMode'] is defined %}
          {% set schedulesMode = value_json['schedulesMode'] %}
        {% else %}
          {% set schedulesMode = 'off' %}
        {% endif %}
  
        {% if deviceOn == true %}
          {% if schedulesMode == 'auto' %}
            auto
          {% else %}
            heat
          {% endif %}
        {% else %}
          off
        {% endif %}
      action_topic: thermostat_123456/thermostat/properties
      action_template: >
        {% if value_json is defined and value_json['systemMode'] is defined %}
          {% set deviceOn = value_json['deviceOn'] %}
        {% else %}
          {% set deviceOn = false %}
        {% endif %}
        
        {% if value_json is defined and value_json['systemMode'] is defined %}
          {% set systemMode = value_json['systemMode'] %}
        {% else %}
          {% set systemMode = 'off' %}
        {% endif %}
        
        {% if deviceOn == true %}
          {% if systemMode == 'cool' %}
            idle
          {% elif systemMode == 'heat' %}
            heating
          {% endif %}
        {% else %}
          off
        {% endif %}
      mode_command_topic: thermostat_123456/thermostat/set
      mode_command_template: >
        {% if value == 'auto' %}
          {{ {'deviceOn':true,'schedulesMode':'auto'} | to_json }}
        {% endif %}
  
        {% if value == 'heat' %}
          {{ {'deviceOn':true,'schedulesMode':'off'} | to_json }}
        {% endif %}
  
        {% if value == 'off' %}
          {{ {'deviceOn':false,'schedulesMode':'off'} | to_json }}
        {% endif %}
      modes:
        - "auto"
        - "heat"
        - "off"
      temperature_unit: C
      temp_step: 0.5
      min_temp: 5
      max_temp: 35
      initial: 20
      qos: 0
```
```

**Comment by robertorobles** [comment]
hello @fraintt I solved the problem calling to queryDeviceState only once and before heartBeatCommand
You can see my tests here https://github.com/klausahrenberg/WThermostatBeca/issues/239#issuecomment-1320701466

Thank you very much for your help!!

**Comment by fraintt** [comment]
Np!
